### ISSUE TITLE
Can't run DotEditor-0.3.1-win64.exe under Win10 x64

### ISSUE THREAD

**Issue by hsluoyz** [vincenthEE/DotEditor#18]
RT

**Comment by higkoo** [comment]
I can successfully run under win10 x64, did you put the graphviz/bin into your system path?
![1](https://user-images.githubusercontent.com/3828931/29760581-ec0bd5d0-8bf6-11e7-8f6a-d9b3ac719333.png)

https://my.oschina.net/higkoo/blog/1524037

**Comment by 0xC4N1** [comment]
I've put it in my system path on Win7 x64.
Using graphviz 2.38 and DotEditor 0.3.1.

**Comment by 0xC4N1** [comment]
Found the mistake. Due to missing permissions I've added `graphviz/bin` to the user environment variable `PATH`, not the system environment variable `PATH`.

The environment variable `PATH` is accessed by `os.environ['PATH']` ([pydot.py#L532](https://github.com/vincenthEE/DotEditor/blob/428e23aa4a06a3a5f05bccbe787f6a9fadbb0500/pydot.py#L532)) which seems to be returning only the system environment when DotEditor is run by double click. Running it via Run dialog (<kbd>CTRL</kbd>+<kbd>r</kbd>) works.

**Comment by hsluoyz** [comment]
I mean I can't even run the installer ``DotEditor-0.3.1-win64.exe``. Nothing happened when I clicked the installer.

**Comment by 0xC4N1** [comment]
It is not an installer. It is the editor. What happens when you run it on command line?

**Comment by hsluoyz** [comment]
OK. I put this binary into ``C:\Windows\System32``, and clicked it. It runs!

But I still think this is a little unfriendly because no warnings show up. Maybe it should be fixed for better UX.

**Comment by blindahl** [comment]
This issue isn't fixed. If I set PATH in a command window to include Graphviz/bin to avoid cluttering up the PATH variable for my user/system it doesn't start. Adding it to PATH variable either locally in that prompt or globally should not really matter in my opinion.
